"""empty message

Revision ID: d01fc1db42ec
Revises: 4cb70f16f161
Create Date: 2025-04-07 23:05:51.889189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd01fc1db42ec'
down_revision = '4cb70f16f161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.String(length=5), nullable=True))
        batch_op.alter_column('age',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('density', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_column('density')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.drop_column('weight')
        batch_op.drop_column('height')

    # ### end Alembic commands ###
